### ISSUE TITLE
Remove dependency on github.com/dgryski/go-metro

### ISSUE THREAD

**Issue by tamird** [jmank88/nuts#2]
github.com/dgryski/go-metro is written largely in gc-syntax assembly, which makes it difficult to support gccgo downstream of it. It would be better if this library (which is used by github.com/golang/dep) did not depend on it.

cc @sdboyer

**Comment by jmank88** [comment]
`go-metro` is only imported by the `cmd/testpaths` package, which is called via `go:generate` from `paths_test`, so perhaps this can be worked around.  On the other hand, its only minimally used and can likely be replaced by any old relatively uniform hash.

**Comment by tamird** [comment]
Right. Why not use the stdlib's [`hash/fnv`](https://godoc.org/hash/fnv)?
